export const curriculum = [
{grade:1,level:"Easy",goal:"Recognise Arabic letters, hear their sounds and use first greetings.",phases:[["First letters",["Letters أ to خ","Letter names and sounds","Picture-letter matching"],"Identify taught letters by sight and sound."],["Complete the alphabet",["Letters د to ي","Similar-looking letters","Alphabet order"],"Recognise all 28 isolated letters."],["First greetings",["أهلاً، مرحباً، شكراً","السلام عليكم","أنا… / اسمي…"],"Greet someone and say a name."]],checks:["Tap the spoken letter","Match picture and letter","Choose a greeting"]},
{grade:1,level:"Medium",goal:"Read connected forms and conduct a guided introduction.",phases:[["Letters in words",["Initial, medial and final forms","Joining letters","Non-connecting letters"],"Recognise letters in every position."],["Useful words",["Short familiar words","أنا، أنتَ، أنتِ، هو، هي","Listen and repeat"],"Read and build familiar words."],["Meet a friend",["Name questions","Introduction dialogue","Countries and languages"],"Complete a two-person introduction."]],checks:["Build a word","Select a pronoun","Complete an introduction"]},
{grade:1,level:"Hard",goal:"Apply the complete Grade 1 syllabus in practical conversations.",phases:[["Travel",["طائرة، تذكرة، مطار","Journey expressions","Listening"],"Understand essential travel words."],["Move around",["Transport","Location words","Town places"],"Follow a simple location response."],["Sports and review",["Sports and equipment","Picture identification","Integrated dialogues"],"Use complete Grade 1 vocabulary."]],checks:["Audio comprehension","Location dialogue","Grade 1 conversation"]},
{grade:2,level:"Easy",goal:"Build nominal and verbal sentences from pictures.",phases:[["Sentence families",["Nominal sentences","Verbal sentences","Who, what and action"],"Sort basic sentence types."],["Connect and ask",["Joining with و","Statements and questions","Picture sentences"],"Turn a statement into a question."],["Words that belong",["Attached pronouns","Singular foundations","Opposites"],"Use taught forms in sentences."]],checks:["Sort sentences","Order word cards","Make a question"]},
{grade:2,level:"Medium",goal:"Use number, gender, tense and prepositions accurately.",phases:[["One, two, many",["Singular and dual","Introductory plurals","Pronoun agreement"],"Choose forms matching number."],["Sound and time",["Sun and moon letters","Past, present, imperative","Masculine and feminine verbs"],"Distinguish patterns and verb time."],["Complete sentences",["ب، من، على، في، لـ","Reorder words","Suitable verbs"],"Construct a correct sentence."]],checks:["Sun/moon sort","Choose tense","Rebuild sentence"]},
{grade:2,level:"Hard",goal:"Master Grade 2 through Maldivian heritage and food contexts.",phases:[["Places and heritage",["Maldivian landmarks","Museum and Friday Mosque","Describe a landmark"],"Discuss a local-history text."],["People and forms",["Islamic Centre","Muhammad Thakurufaanu","Gender and ت / ة"],"Apply forms in context."],["At the table",["Food and tableware","Dining expressions","Grammar review"],"Communicate about food accurately."]],checks:["Heritage reading","Gender editing","Dining dialogue"]},
{grade:3,level:"Easy",goal:"Classify nouns and use singular, dual and plural forms.",phases:[["Food conversations",["Dining expressions","Singular and dual","Table needs"],"Join a food dialogue."],["Many things",["Masculine plural","Feminine plural","Broken plurals"],"Choose a familiar plural."],["Animals and nouns",["Land and marine animals","Signs of a noun","Definite and indefinite"],"Classify familiar nouns."]],checks:["Choose number form","Animal classification","Noun sorting"]},
{grade:3,level:"Medium",goal:"Create consistent nominal and verbal sentences.",phases:[["Describe people",["Appearance and clothing","Subject and predicate","Gender agreement"],"Build an agreeing sentence."],["Pets",["Pet vocabulary","Guided dialogue","Number agreement"],"Describe a pet."],["Work and actions",["Industry and occupations","Verb and doer","Verbal sentences"],"Identify and use the doer."]],checks:["Description builder","Pet dialogue","Find the doer"]},
{grade:3,level:"Hard",goal:"Integrate the complete Grade 3 syllabus independently.",phases:[["Numbers and calendar",["Numbers 1 to 100","Days","Arabic and Gregorian months"],"Use dates and quantities."],["Time and seasons",["Telling time","Four seasons","Daily schedule"],"Discuss time and seasons."],["Directions and mastery",["Four directions","Island map dialogue","Full syllabus review"],"Complete an independent task."]],checks:["Calendar task","Tell time","Map directions","Grade 3 mastery"]}
];
