export type GameKind="Picture Match"|"Sound Hunt"|"Letter Builder"|"Reef Rush";
export type GameRound={id:string;kind:GameKind;prompt:string;visual:string;spoken?:string;pieces?:string[];options:string[];answer:string;hint:string;seconds?:number};
const letters=["أ","ب","ت","ث","ج","ح","خ","د","ذ","ر","ز","س","ش","ص","ض","ط","ظ","ع","غ","ف","ق","ك","ل","م","ن","ه","و","ي"];
const words=[["أَسَد","🦁","أ"],["بَطَّة","🦆","ب"],["تُفَّاح","🍎","ت"],["ثَعْلَب","🦊","ث"],["جَمَل","🐪","ج"],["حُوت","🐋","ح"],["خَرُوف","🐑","خ"],["دُلْفِين","🐬","د"],["ذُرَة","🌽","ذ"],["رُمَّان","🔴","ر"],["زَهْرَة","🌺","ز"],["سَمَك","🐟","س"],["شَمْس","☀️","ش"],["صَدَفَة","🐚","ص"],["ضِفْدَع","🐸","ض"],["طَائِرَة","✈️","ط"],["ظَرْف","✉️","ظ"],["عَيْن","👁️","ع"],["غَيْمَة","☁️","غ"],["فِيل","🐘","ف"],["قَمَر","🌙","ق"],["كِتَاب","📘","ك"],["لَيْمُون","🍋","ل"],["مَوْز","🍌","م"],["نَجْمَة","⭐","ن"],["هِلال","🌙","ه"],["وَرْدَة","🌹","و"],["يَد","✋","ي"]];
const greetings=[["أَهْلًا","👋"],["شُكْرًا","💛"],["اِسْمِي","🙂"],["مَعَ السَّلَامَة","🚶"]];
const rotate=<T,>(a:T[],n:number)=>a.map((_,i)=>a[(i+n)%a.length]);
const kinds:GameKind[]=["Picture Match","Sound Hunt","Letter Builder","Reef Rush"];
export const gamePhase=(level:number)=>level<=7?"Phase 1 · Alphabet lagoon":level<=14?"Phases 1–2 · Word reef":"All phases · Conversation island";
export function gameForLevel(level:number):GameRound[]{return Array.from({length:5},(_,q)=>{const seed=(level-1)*5+q,kind=kinds[(level+q-1)%4],word=words[seed%words.length],letter=letters[seed%letters.length];if(level<=7){const options=rotate([letter,letters[(seed+6)%28],letters[(seed+13)%28]],(seed*3+level)%3);return{id:`G${level}R${q+1}`,kind,prompt:kind==="Letter Builder"?"Build the letter shown.":kind==="Sound Hunt"?"Hear the sound. Catch its letter!":"Tap the letter that starts the picture.",visual:kind==="Sound Hunt"?"🎧":word[1],spoken:letter,pieces:kind==="Letter Builder"?[letter,"ـ"]:undefined,options,answer:letter,hint:`Find the letter ${letter}.`,seconds:kind==="Reef Rush"?15:undefined}}if(level<=14){const options=rotate([word[0],words[(seed+7)%28][0],words[(seed+15)%28][0]],(seed*5+level)%3);return{id:`G${level}R${q+1}`,kind,prompt:kind==="Letter Builder"?"Put the word in the shell.":kind==="Sound Hunt"?"Hear the word. Catch it!":"Match the picture and word.",visual:word[1],spoken:word[0],pieces:kind==="Letter Builder"?Array.from(word[0]).reverse():undefined,options,answer:word[0],hint:`It begins with ${word[2]}.`,seconds:kind==="Reef Rush"?12:undefined}}const greeting=greetings[seed%greetings.length],options=rotate([greeting[0],greetings[(seed+1)%4][0],words[(seed+9)%28][0]],(seed*7+level)%3);return{id:`G${level}R${q+1}`,kind,prompt:kind==="Sound Hunt"?"Hear Nooru. Catch the phrase!":kind==="Letter Builder"?"Build the friendly phrase.":"Choose what Nooru should say.",visual:greeting[1],spoken:greeting[0],pieces:kind==="Letter Builder"?greeting[0].split(" ").reverse():undefined,options,answer:greeting[0],hint:greeting[0]==="أَهْلًا"?"Use this when meeting a friend.":"Look at the picture clue.",seconds:kind==="Reef Rush"?10:undefined}})}
