import type { Lesson } from './grade1-easy';
import type { QuizQuestion } from './quiz-data';
import type { GameRound } from './game-data';

type Check = [prompt: string, answer: string, other: string, another: string, hint: string];
export type ArabicUnit = { title: string; arabic: string; passage: string; checks: Check[]; writing: string; speaking: string; extension: string; pages: number[] };
// Original teaching texts, mapped to NIE KS2 outcome clusters. Titles and tasks are not official textbook chapters.
export const grade4Units: ArabicUnit[] = [
  { title:'Our classroom conversations', arabic:'في صفنا', passage:'قالت المعلمة: افتحوا الكتب، ثم اقرؤوا القصة. سأل علي: هل نقرأ بصوت عالٍ؟ قالت: نعم، وبعد القراءة ناقشوا القصة مع زميل. قال علي: شكرًا، فهمت الآن.',
    checks:[['What should the class do first?','فتح الكتب','إغلاق الكتب','كتابة رسالة','Look at the first instruction.'],['What does Ali ask about?','القراءة بصوت عالٍ','موعد الغداء','لون الكتاب','Read the question after سأل.'],['What happens after reading?','مناقشة القصة','الذهاب إلى البيت','رسم قارب','Find وبعد القراءة.'],['Which word connects two ordered actions?','ثم','هل','علي','It means then.'],['Which response shows understanding?','فهمت الآن','أين الكتاب؟','لم أفهم','Ali now understands.']],
    writing:'Write a classroom request and a helpful reply in Arabic. Use a question mark.', speaking:'With a partner, give two classroom instructions and ask for clarification.', extension:'Explain how the reply answers the request, then improve its politeness.', pages:[17,19,20,23] },
  { title:'A day on our island', arabic:'يوم في جزيرتنا', passage:'أمس زرت جدتي في الصباح. بعد ذلك مشينا إلى الشاطئ، وشاهدنا قاربين. ثم عدنا إلى البيت وتناولنا الغداء. في المساء كتبت عن يومي في دفتري.',
    checks:[['Who did the narrator visit?','جدته','معلمه','طبيبه','Look after زرت.'],['When did the visit happen?','أمس','غدًا','الأسبوع القادم','The opening word gives the time.'],['How many boats were seen?','قاربان','قارب واحد','ثلاثة قوارب','قاربين refers to two.'],['Which action happened last?','الكتابة في الدفتر','زيارة الجدة','المشي إلى الشاطئ','Find في المساء.'],['Which verb describes a completed action?','زرت','أزور','زر','This is a past recount.']],
    writing:'Write a diary entry about a real or imagined day. Give an opening, three ordered events and an ending.', speaking:'Retell the day using first, then and finally. Your partner checks the order.', extension:'Add a feeling and explain its cause.', pages:[17,18,20,23,25] },
  { title:'People and places', arabic:'مكتبة الجزيرة', passage:'مكتبة الجزيرة صغيرة ونظيفة. أمام المكتبة شجرة طويلة، وبجانب الباب نافذتان. داخل المكتبة كتب عربية وقصص مصورة. أمينة المكتبة تساعد الأطفال في اختيار الكتب.',
    checks:[['What place is described?','المكتبة','المطار','المطعم','Read the first sentence.'],['Where is the tree?','أمام المكتبة','داخل المكتبة','خلف البحر','Look for شجرة.'],['How many windows are beside the door?','نافذتان','نافذة واحدة','خمس نوافذ','The ending تان marks two.'],['Choose the agreeing description.','شجرة طويلة','شجرة طويل','شجرة طويلان','شجرة is feminine.'],['Who helps children choose books?','أمينة المكتبة','قائد القارب','الطبيب','The last sentence names the helper.']],
    writing:'Draw a simple plan and write a paragraph describing a place. Use أمام or بجانب and an agreeing adjective.', speaking:'Describe your plan while a partner points to the places you name.', extension:'Explain which details help your listener locate the entrance.', pages:[19,22,23,25] },
  { title:'Read, wonder and retell', arabic:'القلم المفقود', passage:'بحثت مريم عن قلمها تحت الطاولة، فلم تجده. رأت حقيبتها مفتوحة، فنظرت داخلها. وجدت القلم بجانب كتابها وفرحت. قالت: سأضع أدواتي في مكان واحد.',
    checks:[['What is Maryam looking for?','قلمها','قاربها','حذاءها','Find the object after بحثت عن.'],['Where does she find it?','داخل الحقيبة','تحت الطاولة','في البحر','Her first search fails.'],['How does she feel at the end?','فرحة','غاضبة','خائفة','Find وفرحت.'],['Which title fits best?','القلم المفقود','رحلة بحرية','طعام لذيذ','Choose the central problem.'],['What is her plan?','وضع الأدوات في مكان واحد','ترك الحقيبة في البحر','شراء طاولة','Read her final words.']],
    writing:'Retell the beginning, problem and solution in a connected paragraph.', speaking:'Before reading, predict from the title. After reading, explain whether your prediction was right.', extension:'Suggest a different ending that still solves the problem.', pages:[18,20,21,23] },
  { title:'Discover our sea', arabic:'مراقبة الشاطئ', passage:'راقب طلاب الصف الشاطئ صباحًا. سجلوا في جدول: ثلاثة قوارب، وخمسة طيور، وسلحفاة واحدة. لم يلمسوا الحيوانات. كتبوا ملاحظاتهم، ثم رسموا ما شاهدوه.',
    checks:[['When did the observation happen?','صباحًا','ليلًا','بعد منتصف الليل','Find the time in sentence one.'],['Which count is largest?','الطيور','القوارب','السلاحف','Compare five, three and one.'],['How many turtles were recorded?','واحدة','ثلاث','خمس','Read the last item in the list.'],['Which sentence matches the text?','لم يلمسوا الحيوانات','أخذوا السلحفاة','أطعموا الطيور','Look for the negative sentence.'],['Why is a table useful here?','لتنظيم الأعداد','لإخفاء المعلومات','لتغيير الأعداد','A table organizes observations.']],
    writing:'Turn the observations into a three-row table, then write a short factual report.', speaking:'Explain the table to a partner, distinguishing what the class saw from what you imagine.', extension:'Write a question these observations cannot answer.', pages:[17,20,22,23] },
  { title:'Plan a class visit', arabic:'زيارة المتحف', passage:'سنزور المتحف يوم الخميس. قالت المعلمة: أحضروا دفترًا، وابقوا مع المجموعة. سيكتب حسن أسماء الأشياء، وسترسم سارة قاربًا قديمًا. بعد الزيارة سنعرض أعمالنا في الصف.',
    checks:[['Where will the class go?','إلى المتحف','إلى السوق','إلى المطار','The opening gives the destination.'],['What should children bring?','دفترًا','كرة','وسادة','Look after أحضروا.'],['What is Sara’s role?','رسم قارب قديم','كتابة أسماء الأشياء','قيادة الحافلة','Find سارة.'],['Which instruction keeps the group together?','ابقوا مع المجموعة','اذهبوا وحدكم','اتركوا المجموعة','Choose the instruction from the text.'],['When will work be shown?','بعد الزيارة','قبل الزيارة','أثناء النوم','Read the final sentence.']],
    writing:'Write a visit plan with a destination, two instructions and two group roles.', speaking:'Agree on roles with a partner and explain what happens before and after the visit.', extension:'Add a useful clarification question for the teacher.', pages:[17,18,21,23,24] },
  { title:'Words and patterns', arabic:'ركن الكلمات', passage:'كتبت هدى كلمات جديدة في دفترها: كاتب، وكتاب، ومكتبة. لاحظت حروف ك ت ب في الكلمات. بحثت عن معنى كلمة في معجم صغير، ثم كتبت جملة: في المكتبة كتب مفيدة.',
    checks:[['Where does Huda record words?','في دفترها','على القارب','على الباب','Read the opening sentence.'],['Which letters recur in the word family?','ك ت ب','س م ع','ل ع ب','Look at the listed letters.'],['What tool helps her find a meaning?','معجم','ساعة','كرة','A dictionary explains words.'],['Which word is a plural?','كتب','كتاب','كاتب','Choose the form meaning books.'],['What does she do after looking up a meaning?','تكتب جملة','تنام','تغلق المدرسة','Find ثم.']],
    writing:'Make a small vocabulary page: a word, a checked meaning and an original sentence. Reread its spelling.', speaking:'Explain how you checked a meaning. Read your sentence to a partner.', extension:'Compare related words without assuming all related forms mean the same thing.', pages:[19,21,22,24,25] },
  { title:'Explain a good choice', arabic:'لنحافظ على صفنا', passage:'قال عمر: أقترح أن نضع صندوقًا للورق المستعمل في الصف. قالت مريم: لماذا؟ أجاب: لنجمع الورق في مكان واحد ونحافظ على نظافة الصف. اتفق الأصدقاء وكتبوا بطاقة على الصندوق.',
    checks:[['What does Omar propose?','صندوق للورق المستعمل','باب جديد','رحلة إلى البحر','Look after أقترح.'],['Which word asks for a reason?','لماذا','متى','أين','It asks why.'],['What reason does he give?','نظافة الصف','زيادة الضوضاء','إغلاق المدرسة','Read his explanation.'],['What did the friends write?','بطاقة على الصندوق','قصة عن القمر','قائمة طعام','Look at the ending.'],['Which sentence expresses a proposal?','أقترح أن نضع صندوقًا','الصندوق على الطاولة','هذا ورق','أقترح signals a suggestion.']],
    writing:'Write a short proposal to improve your classroom. Include a reason and revise it after feedback.', speaking:'Offer your suggestion; listen to a partner’s question and respond with a reason.', extension:'Consider a different suggestion and explain your preference politely.', pages:[18,20,22,23,24] },
  { title:'Our class exhibition', arabic:'معرض الصف', passage:'نظمنا معرضًا صغيرًا في الصف. عرضت مجموعتنا صور الزيارة، وكتبت تحت كل صورة جملة. شرحت ليلى الصور للزوار، وأجاب سامي عن أسئلتهم. بعد المعرض راجعنا كتاباتنا وصححنا الأخطاء.',
    checks:[['Where was the exhibition?','في الصف','في الحديقة','في المطار','Find the location in the opening.'],['What was written under each picture?','جملة','رقم هاتف','قائمة طعام','The text describes captions.'],['Who explained the pictures?','ليلى','سامي','هدى','Look for شرحت.'],['What did Sami do?','أجاب عن الأسئلة','قاد القارب','طبخ الطعام','Read after سامي.'],['What happened after the exhibition?','مراجعة الكتابات','إلغاء الصور','بدء الرحلة','Find بعد المعرض.']],
    writing:'Prepare a captioned poster and revise one earlier paragraph. Keep the first and improved versions.', speaking:'Present your poster and answer a partner’s question. Ask an adult for feedback on clarity.', extension:'Explain a specific revision and why it helps your audience.', pages:[17,18,20,21,23,24,25] },
];

export const grade5Units: ArabicUnit[] = [
  { title:'Speak for your audience', arabic:'طلب المساعدة', passage:'قالت سلمى لصديقتها: هل تساعدينني في ترتيب الكتب؟ ثم كتبت إلى مديرة المدرسة: نرجو أن تسمحي لنا باستخدام المكتبة لعرض أعمالنا. أرادت سلمى تنظيم معرض للقراءة، فاختارت لكل مخاطب تعبيرًا مناسبًا.',
    checks:[['What does Salma ask her friend to do?','ترتيب الكتب','رسم البحر','شراء طعام','Read the first question.'],['Who receives the written request?','مديرة المدرسة','الطبيبة','قائدة القارب','Find كتبت إلى.'],['Which expression suits the formal request?','نرجو أن تسمحي لنا','أين كرتي؟','هيا نلعب','Consider the audience and purpose.'],['Why does she want the library?','لعرض الأعمال','لبيع الطعام','لإصلاح القارب','Read after باستخدام المكتبة.'],['What changes between the requests?','المخاطب والتعبير','اسم المدرسة فقط','عدد النوافذ','The last sentence explains her choices.']],
    writing:'Write two requests: one to a friend and one to the school principal. Revise the wording for each audience.', speaking:'Role-play both requests and explain the difference in tone.', extension:'Write a respectful follow-up if the principal asks you to explain your plan.', pages:[27,28,30,33,34] },
  { title:'Stories with evidence', arabic:'قبل المطر', passage:'رأت ندى غيومًا داكنة فوق الجزيرة، فأغلقت النوافذ وأدخلت الكتب من الشرفة. قال أخوها: لماذا تسرعين؟ أجابت: أخشى أن تبتل الكتب. بعد قليل بدأ المطر، فابتسمت ندى ونظرت إلى الكتب الجافة.',
    checks:[['Why does Nada bring the books inside?','لحمايتها من المطر','لبيعها','لإخفائها عن المعلمة','Connect her answer with the dark clouds.'],['Which detail suggests rain may come?','غيوم داكنة','كتب جافة','نوافذ مفتوحة','Use evidence before the rain starts.'],['What happens after she protects the books?','يبدأ المطر','تشرق شمس جديدة','تضيع الكتب','Find بعد قليل.'],['Which description is supported?','ندى حريصة','ندى مهملة','ندى غاضبة دائمًا','Her actions protect the books.'],['Which is a summary rather than a minor detail?','حمت ندى الكتب قبل المطر','سأل أخوها سؤالًا','نظرت إلى الكتب','Include the central action and its purpose.']],
    writing:'Summarize the story and support a description of Nada with two actions from the passage.', speaking:'Compare your interpretation with a partner’s. Point to the words supporting each view.', extension:'Write a plausible alternative ending and explain how it changes the impression of Nada.', pages:[28,30,31,32,33] },
  { title:'Island information desk', arabic:'مكتبتان', passage:'النص الأول: تفتح مكتبة المدرسة صباحًا، وتضم كتبًا للطلاب. النص الثاني: تفتح مكتبة الحي صباحًا ومساءً، وتستقبل الأطفال والكبار. توفر المكتبتان أماكن للقراءة، لكن مواعيد العمل والجمهور مختلفان.',
    checks:[['What do both libraries provide?','أماكن للقراءة','غرفًا للنوم','قوارب للصيد','Find the shared feature.'],['Which library opens in the evening?','مكتبة الحي','مكتبة المدرسة','لا واحدة منهما','Read the second text.'],['Who can visit the neighbourhood library?','الأطفال والكبار','المعلمون فقط','الصيادون فقط','Look after تستقبل.'],['Which word introduces contrast?','لكن','صباحًا','كتب','It marks a difference.'],['Which note accurately combines the texts?','المكتبتان للقراءة ومواعيدهما مختلفة','المكتبتان مغلقتان صباحًا','مكتبة المدرسة للكبار فقط','Keep both similarity and difference accurate.']],
    writing:'Create comparison notes, then write a paragraph explaining a similarity and a difference.', speaking:'Recommend one library for an evening visit and cite the relevant detail.', extension:'Identify information still needed before recommending a specific book.', pages:[27,30,31,33,34] },
  { title:'Better descriptions', arabic:'لوحتان للبحر', passage:'رسم حسن بحرًا هادئًا كمرآة، ورسمت هالة أمواجًا عالية. لوحة هالة أكبر من لوحة حسن. وقف الزوار متأملين اللوحتين، وقرأوا الوصف المكتوب تحتهما. قال حسن: الألوان تساعدنا على التعبير عن الشعور.',
    checks:[['What is the calm sea compared to?','مرآة','جبل','شجرة','Look after كـ.'],['Which painting is larger?','لوحة هالة','لوحة حسن','هما متساويتان','Read the comparison.'],['Which word is an active participle?','كاتب','مكتوب','كتاب','كاتب names someone who writes.'],['Which word is a passive participle in the text?','المكتوب','الألوان','أكبر','It describes something that has been written.'],['What does متأملين describe?','حال الزوار عند الوقوف','لون البحر','حجم اللوحة','It tells how the visitors stood.']],
    writing:'Describe a picture using an agreeing adjective and a simple comparison. Expand one sentence with how an action happens.', speaking:'Compare two pictures and explain which language creates a calm or lively impression.', extension:'Use an active or passive participle in a new sentence and explain its meaning in context.', pages:[29,32,33,35] },
  { title:'How we do it', arabic:'إعداد ركن القراءة', passage:'لإعداد ركن القراءة، اختر مكانًا هادئًا أولًا. ثم رتّب الكتب حسب الموضوع، وضع بطاقة على كل رف. بعد ذلك جرّب العثور على كتاب وراجع البطاقات إذا كانت غير واضحة. أخيرًا اشرح لزملائك طريقة استخدام الركن.',
    checks:[['What is the first step?','اختيار مكان هادئ','شرح الطريقة','مراجعة البطاقات','Find أولًا.'],['How should books be arranged?','حسب الموضوع','حسب لون الحذاء','بلا ترتيب','Read after رتّب الكتب.'],['Why try finding a book?','للتحقق من وضوح التنظيم','لإخفاء الكتب','لتغيير المكان دائمًا','The trial helps check the labels.'],['Which verb gives an instruction?','اختر','اختار','يختار','Choose the imperative.'],['What comes last?','شرح طريقة الاستخدام','اختيار المكان','ترتيب الكتب','Find أخيرًا.']],
    writing:'Write ordered instructions for a classroom task. Ask a partner to follow them and revise an unclear step.', speaking:'Explain the process without reading every sentence, then answer a clarification question.', extension:'Explain why the checking step belongs before the final explanation.', pages:[27,29,30,33,35] },
  { title:'Discuss and persuade', arabic:'وقت للقراءة', passage:'اقترحت ليلى تخصيص وقت للقراءة كل يوم. قالت: القراءة تمنحنا فرصة لاكتشاف قصص وأفكار جديدة. قال سامي: أحب الفكرة، لكننا نحتاج أيضًا إلى وقت للحركة. أجابت: يمكن أن نقرأ بعد الاستراحة، فلا نلغي وقت اللعب.',
    checks:[['What does Layla propose?','وقت يومي للقراءة','إلغاء الاستراحة','إغلاق المكتبة','Read the first sentence.'],['What concern does Sami raise?','الحاجة إلى الحركة','لون الكتب','عدد القوارب','He supports reading but raises a concern.'],['How does Layla respond?','القراءة بعد الاستراحة','إلغاء اللعب','رفض الاستماع','Her reply preserves play time.'],['Which sentence is a reason for the proposal?','نكتشف قصصًا وأفكارًا جديدة','هذه نافذة','هذا قارب','Find the supporting benefit.'],['Which response best continues the discussion?','لنجرّب الخطة ثم نراجعها','لن أستمع إليك','أنت مخطئ دائمًا','Choose a respectful response that evaluates the plan.']],
    writing:'Write a proposal with a reason and a response to one concern. Revise after a partner comments.', speaking:'Discuss the proposal, taking turns and accurately restating your partner’s concern.', extension:'Separate the claim, its supporting reason and any evidence that would still be needed.', pages:[27,28,30,32,33,34] },
  { title:'Research and report', arabic:'تقرير عن المكتبة', passage:'أراد الفريق معرفة الكتب المفضلة في الصف. سألوا عشرة طلاب وسجلوا الإجابات: ستة اختاروا القصص، وثلاثة اختاروا كتب الحيوانات، وواحد اختار كتابًا عن الفضاء. كتبوا في التقرير أن القصص كانت الأكثر اختيارًا بين هؤلاء الطلاب.',
    checks:[['How many students were asked?','عشرة','ستة','ثلاثة','Read the sample size.'],['Which category was chosen most?','القصص','كتب الحيوانات','الفضاء','Compare six, three and one.'],['Which conclusion stays within the evidence?','القصص الأكثر اختيارًا بين الطلاب العشرة','كل أطفال العالم يحبون القصص','لا أحد يحب الفضاء','Do not generalize beyond the group asked.'],['What is the source of the report’s numbers?','إجابات الطلاب','تخمين الفريق','ألوان الكتب','Find how the information was collected.'],['Which heading best fits?','اختيارات القراءة في صفنا','طقس الجزيرة','قواعد المرور','Choose the report’s subject.']],
    writing:'Write a short report with a heading, accurate numbers and the source of the information. Check a new word in a dictionary.', speaking:'Present the findings and answer a question about what the survey can and cannot tell us.', extension:'Suggest another source or a larger survey and explain what it could add.', pages:[28,29,30,31,34] },
  { title:"Writers’ workshop", arabic:'من المسودة إلى النص', passage:'كتبت آمنة مسودة عن زيارة المكتبة. قرأتها زميلتها وقالت: البداية واضحة، لكن ترتيب الأحداث يحتاج إلى تعديل. أعادت آمنة ترتيب الجمل وأضافت عنوانًا. ثم راجعت الهمزات وعلامات الترقيم، وكتبت نسخة بخط واضح.',
    checks:[['What did the partner say needed improvement?','ترتيب الأحداث','لون الحقيبة','عدد النوافذ','Read the feedback after لكن.'],['What did Amina add?','عنوانًا','صورة قارب','قائمة طعام','Find أضافت.'],['Which action improves organization?','إعادة ترتيب الجمل','حذف كل الكلمات','تغيير لون القلم فقط','Organization concerns how ideas are ordered.'],['Which spelling is correct?','أحمد','احمد','إحمد','The name starts with hamzat qat above alif.'],['What shows that feedback was used?','عدلت آمنة ترتيب الجمل','تركت المسودة كما هي','أغلقت الدفتر','Connect the comment with the revision.']],
    writing:'Save a draft, ask for feedback, then produce a revised version. Check paragraphs, agreement, hamza and punctuation.', speaking:'Explain two changes to a partner. Read a short part aloud and listen for clarity.', extension:'Evaluate whether the changes improve the intended meaning, not only the spelling.', pages:[28,32,34,35] },
  { title:'Our Arabic showcase', arabic:'عرضنا الجماعي', passage:'أعدت المجموعة عرضًا مدته خمس دقائق عن ركن القراءة. قدمت مريم الموضوع، وشرح علي نتائج الاستطلاع، ثم عرضت هدى اقتراحات التحسين. استخدموا بطاقات قصيرة بدل قراءة التقرير كله. في النهاية أجابوا عن الأسئلة وسجلوا الملاحظات.',
    checks:[['How long is the group presentation?','خمس دقائق','ساعة','دقيقة واحدة','The duration belongs to the whole group.'],['Who explains survey results?','علي','مريم','هدى','Read each speaker’s role.'],['Why use short cards?','لتذكّر النقاط دون قراءة التقرير كله','لإخفاء النتائج','لإلغاء الأسئلة','The text contrasts cards with reading the full report.'],['What follows the presentation?','الإجابة عن الأسئلة','بدء الاستطلاع الأول','حذف الملاحظات','Find في النهاية.'],['Which order matches the presentation?','الموضوع ثم النتائج ثم الاقتراحات','الاقتراحات ثم الموضوع ثم النتائج','النتائج ثم الاقتراحات ثم الموضوع','Follow the speakers’ roles.']],
    writing:'Select and revise a portfolio piece. Prepare brief presentation notes with a beginning, evidence and ending.', speaking:'With a group, deliver a five-minute presentation and answer questions. Ask an adult to observe turn-taking and clarity.', extension:'Compare audience feedback with your own evaluation and identify a specific next step.', pages:[27,28,30,31,33,34,35] },
];

export const ks2UnitsFor = (grade: number) => grade === 4 ? grade4Units : grade5Units;
function orderedOptions(check: Check, seed: number) {
  const options = check.slice(1,4) as string[];
  const offset = seed % options.length;
  return [...options.slice(offset), ...options.slice(0,offset)];
}
export function ks2LessonsFor(grade: number, difficulty: string): Lesson[] {
  return ks2UnitsFor(grade).map((unit,index) => ({
    id:index+1, phase:(Math.floor(index/3)+1) as 1|2|3,
    title:unit.title, arabicTitle:unit.arabic, focus:unit.writing,
    subLessons:unit.checks.map((check,step) => ({
      step:['Read','Listen','Explain','Connect','Review'][step], title:check[0],
      instruction:step===1?'Listen to the passage, then answer. Replay when you need to.':difficulty==='Hard'?'Answer independently and explain which words support your answer.':'Read the passage and use the hint if you need support.',
      letters:[], examples:[{letter:unit.arabic,word:unit.passage,visual:'📖'}],
      task:{prompt:check[0],options:orderedOptions(check,index+step).map(label=>({label,visual:'',correct:label===check[1]})),hint:check[4]},
    })),
  }));
}
export function ks2PracticeFor(grade:number,difficulty:string,set:number):QuizQuestion[] {
  const unit=ks2UnitsFor(grade)[Math.max(0,Math.min(8,set-1))];
  return unit.checks.map((check,index)=>({id:`G${grade}-${difficulty}-U${set}-Q${index+1}`,type:'Reading',visual:'📚',passage:unit.passage,prompt:check[0],options:orderedOptions(check,set+index),answer:check[1],hint:check[4]}));
}
export function ks2GameFor(grade:number,difficulty:string,set:number):GameRound[] {
  return ks2PracticeFor(grade,difficulty,set).map(question=>({id:`game-${question.id}`,kind:'Text Quest',visual:'🏝️',passage:question.passage,prompt:question.prompt,options:question.options,answer:question.answer,hint:question.hint}));
}
